### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by traincrisis** [kurocat471/pretty-in-pink#2]
Is this mod the steel-related train blocks from Dave's Building Extended?

**Comment by kurocat471** [comment]
Dave's Building Extended is deprecated as Dave no longer does modding, this mod uses reworked versions of some of the textures from a later build of DBE with direct permission and help from the artist who made them (pinkmachine). The textures are the only connection to DBE. We do not support DBE nor do we follow Dave's practices such as using MCreator - this mod was partly made to avoid MCreator entirely as MCreator mods like DBE cause enormous backend issues due to how unoptimized they are.

**Comment by traincrisis** [comment]
Oh. I didn't know that, was asking because I haven't downloaded it yet but the images show that it looks like DBE
